### PR TITLE
docker and conda

### PR DESCRIPTION
**Pull request by rjleveque**
Added info on docker, see: http://www.clawpack.org/docker_image.html

and on conda install: http://www.clawpack.org/installing.html

### CODE REVIEW

**Comment by rjleveque** [comment]
It would be great if someone could try out the docker instructions!

**Comment by mandli** [comment]
The docker instructions worked for me except for the following errors from `nosetests`:
```
======================================================================
ERROR: Test multi-layer basic plane-waves.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/clawpack-v5.4.0/geoclaw/tests/multilayer/regression_tests.py", line 42, in setUp
    super(MultilayerTest, self).setUp()
  File "/clawpack-v5.4.0/clawpack/clawutil/test.py", line 158, in setUp
    self.build_executable()
  File "/clawpack-v5.4.0/clawpack/geoclaw/test.py", line 53, in build_executable
    executable_name=executable_name)
  File "/clawpack-v5.4.0/clawpack/clawutil/test.py", line 181, in build_executable
    raise e
CalledProcessError: Command 'cd /clawpack-v5.4.0/geoclaw/tests/multilayer ; make .exe' returned non-zero exit status 2

======================================================================
ERROR: examples.euler_3d.Sedov({'num_output_times': 1, 'num_cells': (16, 16, 16), 'outdir': './_sedov_test_results', 'solver_type': 'classic'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/clawpack-v5.4.0/clawpack/pyclaw/util.py", line 175, in <lambda>
    test = lambda: test_app(application, verifier, test_kwargs)
  File "/clawpack-v5.4.0/clawpack/pyclaw/util.py", line 263, in test_app
    raise VerifyError(err)
VerifyError: /clawpack-v5.4.0/pyclaw/examples/euler_3d/Sedov.py
********************************************************************************
verification function
    def verify_sedov(controller):
        import os
        from clawpack.pyclaw.util import check_diff
        from clawpack.pyclaw import Solution

        thisdir = os.path.dirname(__file__)
        verify_dir = os.path.join(thisdir,'./Sedov_regression')

        # Expected solution
        sol_expected = Solution()
        sol_expected.read(1,path=verify_dir,file_format='hdf',read_aux=False)
        assert sol_expected.t == 0.1
        expected_q = sol_expected.state.q

        # Test solution
        sol_test = Solution()
        sol_test.read(1,path=controller.outdir,
                        file_format=controller.output_format,
                        read_aux=False,
                        options=controller.output_options)
        test_q = sol_test.state.get_q_global()


        if test_q is not None:
            q_err = check_diff(expected_q, test_q, reltol=1e-6)
            if q_err is not None:
                return q_err
        else:
            return

args                 : {'use_petsc': False, 'num_output_times': 1, 'num_cells': (16, 16, 16), 'kernel_language': 'Fortran', 'solver_type': 'classic', 'outdir': './_sedov_test_results'}
norm of expected data: 71.8833212966
norm of test data    : 71.879558627
test error           : 0.0107725438014
reltol  : 1e-06
********************************************************************************

-------------------- >> begin captured stdout << ---------------------
{'use_petsc': False, 'num_output_times': 1, 'num_cells': (16, 16, 16), 'kernel_language': 'Fortran', 'solver_type': 'classic', 'outdir': './_sedov_test_results'}

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: pyclaw.examples.euler_3d.Sedov({'num_output_times': 1, 'num_cells': (16, 16, 16), 'outdir': './_sedov_test_results', 'solver_type': 'classic'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/clawpack-v5.4.0/clawpack/pyclaw/util.py", line 175, in <lambda>
    test = lambda: test_app(application, verifier, test_kwargs)
  File "/clawpack-v5.4.0/clawpack/pyclaw/util.py", line 263, in test_app
    raise VerifyError(err)
VerifyError: /clawpack-v5.4.0/pyclaw/src/pyclaw/examples/euler_3d/Sedov.py
********************************************************************************
verification function
    def verify_sedov(controller):
        import os
        from clawpack.pyclaw.util import check_diff
        from clawpack.pyclaw import Solution

        thisdir = os.path.dirname(__file__)
        verify_dir = os.path.join(thisdir,'./Sedov_regression')

        # Expected solution
        sol_expected = Solution()
        sol_expected.read(1,path=verify_dir,file_format='hdf',read_aux=False)
        assert sol_expected.t == 0.1
        expected_q = sol_expected.state.q

        # Test solution
        sol_test = Solution()
        sol_test.read(1,path=controller.outdir,
                        file_format=controller.output_format,
                        read_aux=False,
                        options=controller.output_options)
        test_q = sol_test.state.get_q_global()


        if test_q is not None:
            q_err = check_diff(expected_q, test_q, reltol=1e-6)
            if q_err is not None:
                return q_err
        else:
            return

args                 : {'use_petsc': False, 'num_output_times': 1, 'num_cells': (16, 16, 16), 'kernel_language': 'Fortran', 'solver_type': 'classic', 'outdir': './_sedov_test_results'}
norm of expected data: 71.8833212966
norm of test data    : 71.879558627
test error           : 0.0107725438014
reltol  : 1e-06
********************************************************************************

-------------------- >> begin captured stdout << ---------------------
{'use_petsc': False, 'num_output_times': 1, 'num_cells': (16, 16, 16), 'kernel_language': 'Fortran', 'solver_type': 'classic', 'outdir': './_sedov_test_results'}
```

Not sure if these are absolutely critical but I think we can fix the multilayer test case by making sure the image includes LAPACK.

**Comment by mandli** [comment]
Also `vim` is not in the image :(

**Comment by rjleveque** [comment]
I'm happy to add `vim`.

Also we should probably add `plotly`, and maybe some other Python modules?

It would probably be good to include LAPACK, unless maybe that makes it much bigger or leads to other problems.  Alternatively we could easily have more than one image available, a minimal one, and one that also includes LAPACK, PETSc, etc.

**Comment by mandli** [comment]
LAPACK should be small (and frankly I am surprised that `-llapack` did not work) but PETSc is a bit of a different matter.  I am not sure how MPI would act on a docker instance though so I am not sure if PETSc is really necessary.

**Comment by ketch** [comment]
The PyClaw test failures are a known bug in scipy 0.18 (that's why we're explicitly sticking to 0.17.1 on Travis); see https://github.com/scipy/scipy/issues/6898.  There is a patch already that fixes them, and 0.19 should be released (including that patch) extremely soon.

I don't see anything that installs matlpotlib (but maybe our setup.py does that).  Maybe you also need to explicitly install the Python package six?  Adding plotly shouldn't hurt (though I think our only usage of it is in a couple of notebooks in apps).  Other fairly obscure optional dependencies include hdf5 and h5py.

**Comment by rjleveque** [comment]
I'm merging this for now in order to do some other updates.  We should continue working on Docker at clawpack/docker-files#1.

**Pull request merged**
