### PR TITLE
added photos from claw-dev events and updated community page

### PR DESCRIPTION
**Pull request by rjleveque**
Any other good photos to add to this collection?

### CODE REVIEW

**Comment by ketch** [comment]
Here's the group photo from HPC 2012:

hpc3-2012-group-photo

I'll find the HPC 2014 one and upload it too.

**Comment by rjleveque** [comment]
Those photos are already there, I believe, in the doc/photos directory.

**Comment by ketch** [comment]
I like these too (also from HPC 2012):


img_8486

img_8505

**Comment by ketch** [comment]
Oh, good.

**Pull request merged**
