### PR TITLE
Fix errors

### PR DESCRIPTION
**Pull request by ketch**
This removes some broken links and makes a few things compatible with Python 3.

### CODE REVIEW

**Comment by ketch** [comment]
Also fixes #153 (though I have no idea if this is exactly the intended photo).

**Comment by rjleveque** [comment]
Yes, that's the photo I had added but forgot to commit and push.

**Comment by rjleveque** [comment]
@ketch: This didn't fix some problems due to docstring formatting in pyclaw routines, e.g. in pyclaw/solvers.html:

```
System Message: ERROR/3 
(/Users/rjl/git/clawpack/clawpack/pyclaw/sharpclaw/solver.py:docstring 
of clawpack.pyclaw.sharpclaw.solver.SharpClawSolver, line 29)

Unexpected indentation.
```

I didn't see a pyclaw PR for this.

**Comment by ketch** [comment]
I think all the remaining Sphinx errors are fixed in the 2 PRs I just submitted (pyclaw and riemann).

**Pull request merged**
