### PR TITLE
Render notebooks using sphinx

### PR DESCRIPTION
**Pull request by ketch**
This PR uses [nbsphinx](https://nbsphinx.readthedocs.io) to natively include Jupyter notebooks in the docs.  Previously we included these in an ad hoc fashion.  This PR has the following advantages:

- No need for ad hoc copying of the notebook files
- Can automatically execute notebooks when docs are compiled (this is done for notebooks with no output) or leave existing output intact (this is done for notebooks with saved output)
- Notebooks can be linked to like any other doc page using :ref:, and can be included in toctrees (where their subheadings can also appear)
- Notebooks are styled using the same theme as the rest of the docs

Additionally, this PR adds a nice overview of all the shallow water Riemann solvers currently in the Riemann repo, with links to examples of their usage (it also includes the solvers in https://github.com/clawpack/riemann/pull/126).

Finally, this PR attempts to start providing more organization to the docs by using subdirectories for the major packages (amrclaw, geoclaw, pyclaw, riemann).  The base directory is getting quite cluttered.  I didn't move files out of that directory yet, but I took the four notebooks that were in 
extra_files/notebooks and put them in appropriate subdirectories.

### CODE REVIEW

**Comment by ketch** [comment]
To compile the docs with this PR, you may need to

    pip install nbsphinx

**Comment by mandli** [comment]
I cannot get this to work.  In place of the notebooks I get the following warning
```
System Message: WARNING/2 (/Users/mandli/src/clawpack/doc/doc/amrclaw.rst, line 34)
toctree contains reference to nonexisting document u’amrclaw/amrclaw_advection_2d_square’
```

**Comment by ketch** [comment]
@mandli I think you would get that error if nbsphinx is somehow not working (since the document in question is a .ipynb rather than .rst).  Can you test your nbsphinx installation on a minimal example?  Maybe create a new sphinx doc project and put a single notebook in it?

**Comment by ketch** [comment]
@mandli I helped @rjleveque get it working.  He got the same error as you the first time, but simply running "make html" a second time fixed it.

**Comment by mandli** [comment]
So this automatically uploads the notebooks to nbviewer?

**Comment by ketch** [comment]
>So this automatically uploads the notebooks to nbviewer?

No, certainly not, as far as I understand.  What makes you think that?

**Comment by mandli** [comment]
Ah, I was looking at some of the old links still.  Works for me.

**Comment by mandli** [comment]
Did you want to move the rest of the notebooks in before merging this?

**Comment by ketch** [comment]
One downside of this is that it makes it less obvious how to download a copy of a notebook.  You can do so by right-clicking the "show source" link in the sidebar and saving the file.  But viewing the notebook on nbviewer or Github is more helpful in this regard.  I found an extension that adds a "Show on Github" link to the sidebar, which will be nice for people who want to download notebooks.  It also adds a "Edit on Github" link which might be great for quickly correcting errors that we spot in the docs.

Do we want to make all the gallery notebooks be rendered by Sphinx, instead of linking to them on nbviewer?

Perhaps I should just merge this and let people look around and get used to it before deciding whether to switch the notebook gallery over.

**Comment by mandli** [comment]
I am not seeing the github links when I build this.

**Comment by ketch** [comment]
Sorry, I didn't commit the template file.  It should work now if you pull again.

**Comment by mandli** [comment]
I think this works fine.

**Comment by ketch** [comment]
I went through the notebooks linked from notebooks.rst.  For the ones that are basically documentation, I put them in the doc repo (if they weren't already there) and now I have Sphinx rendering them.  I added to each a link for downloading the notebook.

For notebooks that are more applications, I'm still pointing to them externally, as I don't think they should be incorporated into the doc repo.  However, I found that for some of them we were pointing to a gist of a notebook that also exists in the app repository.  I changed these links to point to the app repository.  I've opened https://github.com/clawpack/apps/issues/78, suggesting that we store executed versions of the apps notebooks in order to avoid duplicating them as gists.

**Pull request merged**
