### PR TITLE
Clawpack 5x revisions

### PR DESCRIPTION
**Pull request by rjleveque**
- Updated figures and info on permissions.
- Discussion of doc repository.

### CODE REVIEW

**Comment by mandli** [comment]
This looks good.  Could you mark off which issues this address in #115?

**Comment by rjleveque** [comment]
Other than addressing permissions it doesn't fully fix anything.  Regarding font sizes in figures we made some figures larger but since they are taken from other publications (with attribution) we can't really change the font sizes.

**Comment by mandli** [comment]
It looks like you did not check this off so maybe @dlgeorge can provide some guidance on this?

**Comment by dlgeorge** [comment]
sorry...I've been lagging a bit. Do you mean the copyright issue? ...for figures I've provided, copyright shouldn't be an issue. Should I try to relabel these figures?

**Comment by mandli** [comment]
I think we may need to cite the source of the overhead imagery.  Relabeling would also be nice if you can.

**Comment by dlgeorge** [comment]
"overhead imagery"...you mean other than citing Allstadt's paper in the caption? just noticed Randy's comment...yeah, not sure if we can change the figures taken straight from other publications with attribution. I can add some labeling to the meager simulation. Maybe the size increase will suffice for the others?

**Comment by mandli** [comment]
I think the meager figure was the real problem.  As long as we do not change the figure then I think it suffices to just cite the originating paper.  Also the simulation does not have anything labeled in it which might be nice to have.

**Comment by dlgeorge** [comment]
based on the editors comments...do we need to combine some figure panels into single figures and with (a) and (b) etc., other than "right" , "left" in the captions?

**Comment by mandli** [comment]
Yeah although I was planning on doing this as they need to be submitted separately anyway.  Tables as well which is a bit odd.

**Comment by dlgeorge** [comment]
ok...I made a single figure for meager with (a), (b)...I can add that unless it will complicate things...I was under the impression that you have to submit separate files for each "figure" but a multipanel figure is a single figure. (?)

**Comment by mandli** [comment]
Yeah, a multi-panel figure gets flattened to one file I think.  Do it however it makes sense to you and before submission I will turn these all into single files.

**Pull request merged**
