### PR TITLE
another attempt at simplifying install instructions

### PR DESCRIPTION
**Pull request by rjleveque**
Here's another attempt at simplifying the install instructions.

I haven't merged this into the dev branch yet, but you can take a look at the results at 

http://depts.washington.edu/clawpack/sampledocs/new_install/installing.html

and the pages linked from it.  In particular, I tried to move much of the description of other options to a new page

http://depts.washington.edu/clawpack/sampledocs/new_install/installing_more_options.html

### CODE REVIEW

**Comment by ketch** [comment]
I like it.  I do think it would be better to put the long pip install command as first option, since that one gives you a  full working install while the one listed first now only gives you pyclaw (sorry if it sounds like I am contradicting what I asked for earlier...)

**Review by mandli — APPROVED** [review]
Looks great to me!

**Comment by mjberger** [comment]
Looks good.

 — Marsha

**Comment by rjleveque** [comment]
I modified as @ketch suggested and a couple other tweaks.  Updated at

http://depts.washington.edu/clawpack/sampledocs/new_install/installing.html

**Comment by rjleveque** [comment]
Some more modifications after discussing with @donnaaboise - some additional information and warnings about using pip.

Updated at http://depts.washington.edu/clawpack/sampledocs/new_install/installing.html

**Comment by rjleveque** [comment]
I'm going to finally merge this, and will push it also to the v5.5.0 branch so it shows up in the main docs.

**Pull request merged**
