### PR TITLE
Adding preliminary doxygen documentation for amrclaw

### PR DESCRIPTION
**Pull request by xinshengqin**
After playing around with sphinx and looking for its support for auto-documenting Fortran code, I turned to Doxygen for writing documentation for amrclaw.

The feature I would like such a package to have is to automatically extract API information written in the code and turn it into html or pdf. Sphinx is really powerful when it handles Python code. The only extension to sphinx for documenting Fortran I found is http://sphinx-fortran.readthedocs.io/en/latest/ but it does not have many instruction on how to use it and is not maintained anymore. 

Doxygen is design for C/C++ originally and later extend to Fortran. I found this example from NASA online about using Doxygen to write documentation for Fortran. I tested Doxygen with two files in amrclaw/2d and it looks very nice. 

I added a folder, $CLAW/doc/doc/doxygen/amrclaw/2d, where the configuration file for doxygen is put. To generate documentation for $CLAW/amrclaw/src/2d, you can simply type doxygen doxygen.conf in $CLAW/doc/doc/doxygen/amrclaw/2d. This will generate a ./doc/html folder where you can open the webpage. After you open the webpage, you can go to Files and click on filpatch.f90. There you can see what a documentation webpage for a fortran file looks like. It contains API, callergraph and callgraph of the function filrecur() inside. Note that this only works after I can also pull my modification to filpatch.f90 to amrclaw repository.

### CODE REVIEW

**Comment by mandli** [comment]
I have tried out the sphinx-fortran plugin and was not able to get it to work either.  Doxygen is pretty standard and used in many Fortran codes so is a pretty safe-bet.  The big question I would have though is how to bridge between sphinx and doxygen.  Would we use hard links between these?  Is there someway to incorporate both doc trees easily?

**Comment by xinshengqin** [comment]
I have also searched for "bridge" between the two and converter from doxygen to sphinx. There are several like breathe and pandoc but it's not easy.  I tried one of them but didn't get it work. 

My thought is to just set a link from the sphinx amrclaw webpage to the root webpage of the "website" generated by doxygen.

**Comment by rjleveque** [comment]
This is a good idea.  I got it to work after [installing doxygen](http://www.stack.nl/~dimitri/doxygen/download.html), which also required [installing cmake](https://cmake.org/download/).

I put this draft of the html files online if anyone wants to look at them without having to generate them: https://depts.washington.edu/clawpack/amrclaw_doxygen/globals_func.html

**Comment by xinshengqin** [comment]
@rjleveque I just checked the webpage you put online. It haven't showed what's cool about Doxygen yet since the amrclaw repository has not been updated (merged). You might need to rerun doxygen after my pull request clawpack/amrclaw#189 get merged.

**Comment by rjleveque** [comment]
I guess I have to install graphviz to get the call graphs to show up?

**Comment by mandli** [comment]
Do we have a plan for when we want to merge this?  Would we rather merge this now and incrementally add docs as we go or wait until there's more substantial progress?  For the record I favor the former.

**Comment by xinshengqin** [comment]
Actually I made this pull request to ask for your opinions on this in case I go in the wrong direction. 
If you think this is good, I will add more documentation in this form.

**Comment by rjleveque** [comment]
I updated the example output files at https://depts.washington.edu/clawpack/amrclaw_doxygen/globals_func.html

To see how the call graphs look, see for example
https://depts.washington.edu/clawpack/amrclaw_doxygen/filpatch_8f90.html#a842d63d44af2ea44724f2ee0c374438e

Before merging we need to add a link from the sphinx docs to these docs.  I will do this once we get some of the other sphinx changes merged in.

**Comment by rjleveque** [comment]
I'm going to go ahead and merge this and will shortly issue a PR that adds a pointer from the Sphinx docs.

**Pull request merged**
